KLEE: Using STP solver backend
KLEE: ERROR: projeto1.c:427: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:345: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:366: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:370: memory error: object read only
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:370: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:271: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:175: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:179: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:179: memory error: object read only
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:275: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:597: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:350: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:277: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:601: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:275: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:352: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto1.c:357: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
